from typing import Protocol


class AuthTokenRepository(Protocol):
    async def create(self, email: str) -> str: ...

    async def find(self, email: str) -> str | None: ...

    async def store(self, token: str) -> None: ...

    async def revoke(self, token: str) -> None: ...

    async def remove(self, token: str) -> None: ...
