"""update database schema

Revision ID: 10643e7eb0bc
Revises: ed508a940d6a
Create Date: 2026-07-31 12:24:32.580947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10643e7eb0bc'
down_revision: Union[str, Sequence[str], None] = 'ed508a940d6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('document', 'mime_type',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('document', 'bucket_name',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('document', 'bucket_name',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('document', 'mime_type',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
