"""initial database schema

Revision ID: 18a445388927
Revises: b54d27e29e92
Create Date: 2026-07-30 15:41:28.597771

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "18a445388927"
down_revision: str | Sequence[str] | None = "b54d27e29e92"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    userrole = sa.Enum("ADMIN", "USER", name="userrole")

    userrole.create(op.get_bind(), checkfirst=True)

    op.add_column(
        "users",
        sa.Column("roles", sa.ARRAY(userrole), nullable=False, server_default="{USER}"),
    )

    op.alter_column("users", "roles", server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "roles")

    sa.Enum("ADMIN", "USER", name="userrole").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
