"""update ingestion job  database schema

Revision ID: 2ce40feb2009
Revises: f1c3cde5fe54
Create Date: 2026-09-14 22:09:51.861518

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "2ce40feb2009"
down_revision: str | Sequence[str] | None = "f1c3cde5fe54"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "document_chunk", "document_id", existing_type=sa.UUID(), nullable=False
    )
    op.drop_index(op.f("ix_document_chunk_chunk_hash"), table_name="document_chunk")
    op.drop_index(op.f("ix_document_chunk_neo4j_node_id"), table_name="document_chunk")
    op.drop_index(
        op.f("ix_document_chunk_qdrant_point_id"), table_name="document_chunk"
    )
    op.create_index(
        "ix_chunk_chunk_hash", "document_chunk", ["chunk_hash"], unique=False
    )
    op.create_index(
        "ix_chunk_neo4j_node_id", "document_chunk", ["neo4j_node_id"], unique=False
    )
    op.create_index(
        "ix_chunk_qdrant_point_id", "document_chunk", ["qdrant_point_id"], unique=False
    )
    op.add_column(
        "ingestion_job",
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.alter_column(
        "ingestion_job", "document_id", existing_type=sa.UUID(), nullable=False
    )
    op.alter_column(
        "ingestion_job",
        "workflow_run_id",
        existing_type=sa.VARCHAR(length=255),
        nullable=True,
    )
    op.create_index(
        "ix_job_workflow_id", "ingestion_job", ["workflow_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_job_workflow_id", table_name="ingestion_job")
    op.alter_column(
        "ingestion_job",
        "workflow_run_id",
        existing_type=sa.VARCHAR(length=255),
        nullable=False,
    )
    op.alter_column(
        "ingestion_job", "document_id", existing_type=sa.UUID(), nullable=True
    )
    op.drop_column("ingestion_job", "payload")
    op.drop_index("ix_chunk_qdrant_point_id", table_name="document_chunk")
    op.drop_index("ix_chunk_neo4j_node_id", table_name="document_chunk")
    op.drop_index("ix_chunk_chunk_hash", table_name="document_chunk")
    op.create_index(
        op.f("ix_document_chunk_qdrant_point_id"),
        "document_chunk",
        ["qdrant_point_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_document_chunk_neo4j_node_id"),
        "document_chunk",
        ["neo4j_node_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_document_chunk_chunk_hash"),
        "document_chunk",
        ["chunk_hash"],
        unique=False,
    )
    op.alter_column(
        "document_chunk", "document_id", existing_type=sa.UUID(), nullable=True
    )
    # ### end Alembic commands ###
