"""add chunk database schema

Revision ID: 38862885c5ff
Revises: f9c6b0a30d07
Create Date: 2026-08-02 19:21:42.112279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '38862885c5ff'
down_revision: Union[str, Sequence[str], None] = 'f9c6b0a30d07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_chunk',
    sa.Column('chunk_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('section_title', sa.String(length=255), nullable=True),
    sa.Column('token_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('chunk_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source_locator', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['document.document_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('chunk_id')
    )
    op.create_index('ix_chunk_created_at', 'document_chunk', ['created_at'], unique=False)
    op.create_index('ix_chunk_document_order', 'document_chunk', ['document_id', 'chunk_index'], unique=False)
    op.create_index('ix_chunk_page_number', 'document_chunk', ['page_number'], unique=False)
    op.create_index('ix_chunk_section_title', 'document_chunk', ['section_title'], unique=False)
    op.create_index(op.f('ix_document_chunk_chunk_id'), 'document_chunk', ['chunk_id'], unique=False)
    op.create_index(op.f('ix_document_chunk_document_id'), 'document_chunk', ['document_id'], unique=False)
    op.create_index('ix_credentials_created_at', 'credentials', ['created_at'], unique=False)
    op.create_index('ix_credentials_provider', 'credentials', ['provider'], unique=False)
    op.create_index('ix_credentials_status', 'credentials', ['status'], unique=False)
    op.create_index('ix_document_created_at', 'document', ['created_at'], unique=False)
    op.create_index('ix_document_status', 'document', ['status'], unique=False)
    op.create_index('ix_tenant_created_at', 'tenant', ['created_at'], unique=False)
    op.create_index('ix_tenant_organisation', 'tenant', ['organisation'], unique=False)
    op.create_index('ix_tenant_status', 'tenant', ['status'], unique=False)
    op.create_index('ix_user_created_at', 'users', ['created_at'], unique=False)
    op.create_index('ix_user_status', 'users', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_status', table_name='users')
    op.drop_index('ix_user_created_at', table_name='users')
    op.drop_index('ix_tenant_status', table_name='tenant')
    op.drop_index('ix_tenant_organisation', table_name='tenant')
    op.drop_index('ix_tenant_created_at', table_name='tenant')
    op.drop_index('ix_document_status', table_name='document')
    op.drop_index('ix_document_created_at', table_name='document')
    op.drop_index('ix_credentials_status', table_name='credentials')
    op.drop_index('ix_credentials_provider', table_name='credentials')
    op.drop_index('ix_credentials_created_at', table_name='credentials')
    op.drop_index(op.f('ix_document_chunk_document_id'), table_name='document_chunk')
    op.drop_index(op.f('ix_document_chunk_chunk_id'), table_name='document_chunk')
    op.drop_index('ix_chunk_section_title', table_name='document_chunk')
    op.drop_index('ix_chunk_page_number', table_name='document_chunk')
    op.drop_index('ix_chunk_document_order', table_name='document_chunk')
    op.drop_index('ix_chunk_created_at', table_name='document_chunk')
    op.drop_table('document_chunk')
    # ### end Alembic commands ###
