"""update database schema

Revision ID: a736953ae31a
Revises: e185a74c33ff
Create Date: 2026-08-03 15:57:37.849520

"""
from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a736953ae31a'
down_revision: str | Sequence[str] | None = 'e185a74c33ff'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_job_attempt_count', 'ingestion_job', ['attempt_count'], unique=False)
    op.create_index('ix_job_workflow_run_id', 'ingestion_job', ['workflow_run_id'], unique=False)
    op.create_index('ix_user_email', 'users', ['email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_email', table_name='users')
    op.drop_index('ix_job_workflow_run_id', table_name='ingestion_job')
    op.drop_index('ix_job_attempt_count', table_name='ingestion_job')
    # ### end Alembic commands ###
