"""update database schema

Revision ID: e185a74c33ff
Revises: 38862885c5ff
Create Date: 2026-08-02 19:39:06.661926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e185a74c33ff'
down_revision: Union[str, Sequence[str], None] = '38862885c5ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('credentials', 'password_hash',
               existing_type=sa.TEXT(),
               nullable=True)
    op.create_unique_constraint('uq_user_provider', 'credentials', ['user_id', 'provider'])
    op.alter_column('document_chunk', 'content',
               existing_type=sa.TEXT(),
               nullable=False)
    op.create_unique_constraint('uq_document_chunk_index', 'document_chunk', ['document_id', 'chunk_index'])
    op.add_column('ingestion_job', sa.Column('workflow_run_id', sa.String(length=255), nullable=False))
    op.alter_column('ingestion_job', 'workflow_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_constraint(op.f('ingestion_job_workflow_id_key'), 'ingestion_job', type_='unique')
    op.create_unique_constraint(None, 'ingestion_job', ['workflow_run_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ingestion_job', type_='unique')
    op.create_unique_constraint(op.f('ingestion_job_workflow_id_key'), 'ingestion_job', ['workflow_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('ingestion_job', 'workflow_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('ingestion_job', 'workflow_run_id')
    op.drop_constraint('uq_document_chunk_index', 'document_chunk', type_='unique')
    op.alter_column('document_chunk', 'content',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_constraint('uq_user_provider', 'credentials', type_='unique')
    op.alter_column('credentials', 'password_hash',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
