"""update database schema

Revision ID: ed508a940d6a
Revises: 18a445388927
Create Date: 2026-07-30 18:46:29.722535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed508a940d6a'
down_revision: Union[str, Sequence[str], None] = '18a445388927'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_credentials_credentials_id'), 'credentials', ['credentials_id'], unique=False)
    op.create_index(op.f('ix_credentials_user_id'), 'credentials', ['user_id'], unique=False)
    op.create_index(op.f('ix_document_document_id'), 'document', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_tenant_id'), 'document', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_tenant_tenant_id'), 'tenant', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_index(op.f('ix_tenant_tenant_id'), table_name='tenant')
    op.drop_index(op.f('ix_document_tenant_id'), table_name='document')
    op.drop_index(op.f('ix_document_document_id'), table_name='document')
    op.drop_index(op.f('ix_credentials_user_id'), table_name='credentials')
    op.drop_index(op.f('ix_credentials_credentials_id'), table_name='credentials')
    # ### end Alembic commands ###
