"""initial database schema

Revision ID: f1c3cde5fe54
Revises: 
Create Date: 2026-09-14 15:49:10.600272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f1c3cde5fe54'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenant',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('organisation', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'ACTIVE', 'SUSPENDED', name='tenantstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('tenant_id')
    )
    op.create_index('ix_tenant_created_at', 'tenant', ['created_at'], unique=False)
    op.create_index('ix_tenant_organisation', 'tenant', ['organisation'], unique=False)
    op.create_index('ix_tenant_status', 'tenant', ['status'], unique=False)
    op.create_index(op.f('ix_tenant_tenant_id'), 'tenant', ['tenant_id'], unique=False)
    op.create_table('document',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=255), nullable=True),
    sa.Column('document_type', sa.Enum('PDF', 'DOCX', 'DOC', 'MARKDOWN', 'CSV', 'HTML', 'IMAGE', 'PPTX', name='documenttype'), nullable=True),
    sa.Column('language', sa.Enum('ENGLISH', name='languagetype'), nullable=True),
    sa.Column('bucket_name', sa.Text(), nullable=True),
    sa.Column('storage_key', sa.Text(), nullable=False),
    sa.Column('storage_provider', sa.Enum('MINIO', 'S3', 'AZURE', 'LOCAL', name='storageprovider'), nullable=True),
    sa.Column('version_id', sa.String(length=255), nullable=True),
    sa.Column('etag', sa.String(length=255), nullable=True),
    sa.Column('checksum', sa.String(length=64), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), server_default='-1', nullable=False),
    sa.Column('status', sa.Enum('UPLOAD_PENDING', 'UPLOADED', 'READY', 'FAILED', 'DELETED', name='documentstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.tenant_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('document_id')
    )
    op.create_index(op.f('ix_document_checksum'), 'document', ['checksum'], unique=False)
    op.create_index('ix_document_created_at', 'document', ['created_at'], unique=False)
    op.create_index(op.f('ix_document_document_id'), 'document', ['document_id'], unique=False)
    op.create_index('ix_document_status', 'document', ['status'], unique=False)
    op.create_index(op.f('ix_document_tenant_id'), 'document', ['tenant_id'], unique=False)
    op.create_table('users',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('roles', sa.ARRAY(sa.Enum('ADMIN', 'USER', name='userrole')), nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'ACTIVE', 'DISABLED', name='userstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.tenant_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('ix_user_created_at', 'users', ['created_at'], unique=False)
    op.create_index('ix_user_email', 'users', ['email'], unique=False)
    op.create_index('ix_user_status', 'users', ['status'], unique=False)
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    op.create_table('credentials',
    sa.Column('credentials_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('CREATED', 'VALID', 'REVOKED', name='credentialstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('password_changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('credentials_id'),
    sa.UniqueConstraint('user_id', 'provider', name='uq_user_provider')
    )
    op.create_index('ix_credentials_created_at', 'credentials', ['created_at'], unique=False)
    op.create_index(op.f('ix_credentials_credentials_id'), 'credentials', ['credentials_id'], unique=False)
    op.create_index('ix_credentials_provider', 'credentials', ['provider'], unique=False)
    op.create_index('ix_credentials_status', 'credentials', ['status'], unique=False)
    op.create_index(op.f('ix_credentials_user_id'), 'credentials', ['user_id'], unique=False)
    op.create_table('document_chunk',
    sa.Column('chunk_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('token_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('section_title', sa.String(length=255), nullable=True),
    sa.Column('chunk_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source_locator', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('chunk_hash', sa.String(length=64), nullable=True),
    sa.Column('qdrant_point_id', sa.UUID(), nullable=True),
    sa.Column('neo4j_node_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['document.document_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('chunk_id'),
    sa.UniqueConstraint('document_id', 'chunk_index', name='uq_document_chunk_index')
    )
    op.create_index('ix_chunk_created_at', 'document_chunk', ['created_at'], unique=False)
    op.create_index('ix_chunk_document_order', 'document_chunk', ['document_id', 'chunk_index'], unique=False)
    op.create_index('ix_chunk_page_number', 'document_chunk', ['page_number'], unique=False)
    op.create_index('ix_chunk_section_title', 'document_chunk', ['section_title'], unique=False)
    op.create_index(op.f('ix_document_chunk_chunk_hash'), 'document_chunk', ['chunk_hash'], unique=False)
    op.create_index(op.f('ix_document_chunk_chunk_id'), 'document_chunk', ['chunk_id'], unique=False)
    op.create_index(op.f('ix_document_chunk_document_id'), 'document_chunk', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_chunk_neo4j_node_id'), 'document_chunk', ['neo4j_node_id'], unique=False)
    op.create_index(op.f('ix_document_chunk_qdrant_point_id'), 'document_chunk', ['qdrant_point_id'], unique=False)
    op.create_table('ingestion_job',
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('workflow_id', sa.String(length=255), nullable=True),
    sa.Column('workflow_run_id', sa.String(length=255), nullable=False),
    sa.Column('current_stage', sa.Enum('DOWNLOAD', 'PARSING', 'CHUNKING', 'EMBEDDING', 'GRAPH_BUILDING', 'EVALUATION', name='ingestionstage'), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', name='processingstatus'), nullable=False),
    sa.Column('attempt_count', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['document.document_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('job_id'),
    sa.UniqueConstraint('workflow_run_id')
    )
    op.create_index(op.f('ix_ingestion_job_document_id'), 'ingestion_job', ['document_id'], unique=False)
    op.create_index(op.f('ix_ingestion_job_job_id'), 'ingestion_job', ['job_id'], unique=False)
    op.create_index('ix_job_attempt_count', 'ingestion_job', ['attempt_count'], unique=False)
    op.create_index('ix_job_stage', 'ingestion_job', ['current_stage'], unique=False)
    op.create_index('ix_job_status', 'ingestion_job', ['status'], unique=False)
    op.create_index('ix_job_workflow_run_id', 'ingestion_job', ['workflow_run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_job_workflow_run_id', table_name='ingestion_job')
    op.drop_index('ix_job_status', table_name='ingestion_job')
    op.drop_index('ix_job_stage', table_name='ingestion_job')
    op.drop_index('ix_job_attempt_count', table_name='ingestion_job')
    op.drop_index(op.f('ix_ingestion_job_job_id'), table_name='ingestion_job')
    op.drop_index(op.f('ix_ingestion_job_document_id'), table_name='ingestion_job')
    op.drop_table('ingestion_job')
    op.drop_index(op.f('ix_document_chunk_qdrant_point_id'), table_name='document_chunk')
    op.drop_index(op.f('ix_document_chunk_neo4j_node_id'), table_name='document_chunk')
    op.drop_index(op.f('ix_document_chunk_document_id'), table_name='document_chunk')
    op.drop_index(op.f('ix_document_chunk_chunk_id'), table_name='document_chunk')
    op.drop_index(op.f('ix_document_chunk_chunk_hash'), table_name='document_chunk')
    op.drop_index('ix_chunk_section_title', table_name='document_chunk')
    op.drop_index('ix_chunk_page_number', table_name='document_chunk')
    op.drop_index('ix_chunk_document_order', table_name='document_chunk')
    op.drop_index('ix_chunk_created_at', table_name='document_chunk')
    op.drop_table('document_chunk')
    op.drop_index(op.f('ix_credentials_user_id'), table_name='credentials')
    op.drop_index('ix_credentials_status', table_name='credentials')
    op.drop_index('ix_credentials_provider', table_name='credentials')
    op.drop_index(op.f('ix_credentials_credentials_id'), table_name='credentials')
    op.drop_index('ix_credentials_created_at', table_name='credentials')
    op.drop_table('credentials')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_index('ix_user_status', table_name='users')
    op.drop_index('ix_user_email', table_name='users')
    op.drop_index('ix_user_created_at', table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_document_tenant_id'), table_name='document')
    op.drop_index('ix_document_status', table_name='document')
    op.drop_index(op.f('ix_document_document_id'), table_name='document')
    op.drop_index('ix_document_created_at', table_name='document')
    op.drop_index(op.f('ix_document_checksum'), table_name='document')
    op.drop_table('document')
    op.drop_index(op.f('ix_tenant_tenant_id'), table_name='tenant')
    op.drop_index('ix_tenant_status', table_name='tenant')
    op.drop_index('ix_tenant_organisation', table_name='tenant')
    op.drop_index('ix_tenant_created_at', table_name='tenant')
    op.drop_table('tenant')
    # ### end Alembic commands ###
