"""add ingestion database schema

Revision ID: f9c6b0a30d07
Revises: 5419d3d3e5de
Create Date: 2026-08-02 18:04:46.367075

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f9c6b0a30d07"
down_revision: Union[str, Sequence[str], None] = "5419d3d3e5de"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ingestion_job",
        sa.Column("job_id", sa.UUID(), nullable=False),
        sa.Column("document_id", sa.UUID(), nullable=True),
        sa.Column("workflow_id", sa.String(length=255), nullable=False),
        sa.Column(
            "current_stage",
            sa.Enum(
                "DOWNLOAD",
                "PARSING",
                "CHUNKING",
                "EMBEDDING",
                "GRAPH_BUILDING",
                "EVALUATION",
                name="ingestionstage",
            ),
            nullable=True,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "RUNNING",
                "COMPLETED",
                "FAILED",
                "CANCELLED",
                name="processingstatus",
            ),
            nullable=False,
        ),
        sa.Column("attempt_count", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["document_id"], ["document.document_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("job_id"),
        sa.UniqueConstraint("workflow_id"),
    )
    op.create_index(
        op.f("ix_ingestion_job_document_id"),
        "ingestion_job",
        ["document_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ingestion_job_job_id"), "ingestion_job", ["job_id"], unique=False
    )
    op.create_index("ix_job_stage", "ingestion_job", ["current_stage"], unique=False)
    op.create_index("ix_job_status", "ingestion_job", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_job_status", table_name="ingestion_job")
    op.drop_index("ix_job_stage", table_name="ingestion_job")
    op.drop_index(op.f("ix_ingestion_job_job_id"), table_name="ingestion_job")
    op.drop_index(op.f("ix_ingestion_job_document_id"), table_name="ingestion_job")
    op.drop_table("ingestion_job")
    # ### end Alembic commands ###
